repository_type: modules
org_path: nf-core

update:
  https://github.com/nf-core/modules.git:
    nf-core:
      fasta_vclust_fastatsv: False
      fasta_seqhasher_fasta: False
      fasta_genomad_faatsv: False
      fasta_checkv_tsv: False
      vtdb/filtersequences: False
      vtdb/compositionfilter: False
      vtdb/completenessfilter: False
      vtdb/combinedata: False
      vtdb/classificationfilter: False
      viromeqc/viromeqc: False
      viromeqc/install: False
      vclust/cluster: False
      vclust/prefilter: False
      vclust/align: False
      trtrimmer: False
      trfinder: False
      tantan: False
      sra/sratools: False
      sequencestats: False
      seqhasher/sequniq: False
      seqhasher/seqhasher: False
      pyrodigalgv: False
      pyhmmer/virusclassify: False
      pyhmmer/plasmidclassify: False
      pyhmmer/buscoclassify: False
      plass/penguin: False
      phables/run: False
      phables/install: False
      logan/unitigawsclimultiplier: False
      logan/contigawsclimultiplier: False
      logan/contigawscli: False
      checkv/genbankhits: False
      ena/aria2seqkittrfinder: False
      coverm/contig: False
      allthebacteria/aria2seqkittrfinder: False
