channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::biopython=1.84
  - bioconda::hmmer=3.4
  - bioconda::sra-tools=3.1.1
  - bioconda::fastp=0.23.4
  - bioconda::mvirs=1.1.1
  - conda-forge::pandas=2.2.3
