channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::python=3.12.3
  - conda-forge::biopython=1.84
  - conda-forge::pandas=2.2.3
  - bioconda::prodigal-gv=2.11.0
  - bioconda::hmmer=3.4
